#!/bin/bash
setup(){
    #python3.11 -m venv venv
    python3.12 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements_p3.12.txt
}
deploy_i3(){
    source deploy/i3.sh
}
setup
