- name: "{{ label }}"
  ansible.builtin.pause:
    prompt: "{{ label }} [{{ 'Y/n' if default_answer == 'y' else 'y/N' }}]"
  register: _prompt

- ansible.builtin.include_tasks: "../roles/{{ role }}.yaml"
  when: _prompt.user_input | default(default_answer, true) | lower == 'y'
