- name: Create Flameshot directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Applications/Flameshot"
    state: directory
    mode: "0755"

- name: Kill running Flameshot instances
  ansible.builtin.command: pkill -fi flameshot
  failed_when: false

- name: Remove old Flameshot files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/Applications/Flameshot/squashfs-root"
    - "{{ ansible_user_dir }}/Applications/Flameshot/flameshot.sh"
    - "{{ ansible_user_dir }}/.config/i3/flameshot.sh"

- name: Download Flameshot v13.3.0 AppImage
  ansible.builtin.get_url:
    url: https://github.com/flameshot-org/flameshot/releases/download/v13.3.0/Flameshot-13.3.0.x86_64.AppImage
    dest: "{{ ansible_user_dir }}/Applications/Flameshot/Flameshot.AppImage"
    mode: "0755"

- name: Restart xdg-desktop-portal
  ansible.builtin.systemd:
    name: xdg-desktop-portal
    state: started
    scope: user
  ignore_errors: true
