- name: Redeploy i3 configs
  hosts: all
  gather_facts: true

  vars_prompt:
    - name: font_size_choice
      prompt: "Font size? [S]mall / [L]arge"
      default: "s"
      private: false

  tasks:
    - ansible.builtin.include_tasks:
        file: ../roles/i3_setup.yaml
