#!/bin/bash

# Check for mouse button press and handle the actions
if [[ $BLOCK_BUTTON == 1 ]]; then
    # Left click action for launching galendae
    cd /code/linux_apps/galendae-main && ./galendae -c config/dark.conf &

    # Left click action for displaying the calendar
    yad --calendar --undecorated --fixed --close-on-unfocus --no-buttons --posx=-150 --posy=-20 > /dev/null &
fi

# Display the current time for both Los Angeles (LA) and Chicago
echo "⛥: $(TZ='America/Chicago' date '+%a %Y-%m-%d %I:%M:%S %p') ⛧: $(TZ='America/Los_Angeles' date '+%a %I:%M:%S %p')"
