#!/bin/bash

# Check for mouse button press
if [[ $BLOCK_BUTTON == 1 ]]; then
    # Left click
    cd /code/linux_apps/galendae-main; ./galendae -c config/dark.conf &
fi

# Always show the date
export TZ='America/Chicago'; date '+Local/CT: %Y-%m-%d %I:%M:%S %p'
