#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")/../.." ; pwd -P )
if ! grep -q "^joly_linux=" /etc/environment; then
    sudo sed -i '/^joly_linux=/d' /etc/environment
    echo "joly_linux='${parent_path}'" | sudo tee -a /etc/environment
fi
cd $parent_path